//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeSureProject.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee
    {
        public int EmployeeId { get; set; }
        public string EmployeePhoto { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeTitle { get; set; }
        public string EmployeeLinkedIn { get; set; }
        public string EmployeeInstagram { get; set; }
    }
}
