//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeSureProject.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFeature
    {
        public int FeatureId { get; set; }
        public string FeatureTitle { get; set; }
        public string FeatureDescription { get; set; }
        public string FeatureOtherDescription { get; set; }
        public string FeatureLink { get; set; }
        public string VideoUrl { get; set; }
        public string ImageUrl { get; set; }
    }
}
