//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeSureProject.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblService
    {
        public int ServiceId { get; set; }
        public string ServiceImg { get; set; }
        public string ServiceIcon { get; set; }
        public string ServiceTitle { get; set; }
        public string ServiceDescription { get; set; }
        public string ServiceQuestionTitle { get; set; }
        public string ServiceQuestionAnswer { get; set; }
    }
}
